/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedBillingRouteImport } from './routes/_protected/billing'
import { Route as ApiMcpServersRouteImport } from './routes/api/mcp/servers'
import { Route as ApiMcpConnectRouteImport } from './routes/api/mcp/connect'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiBillingSummaryRouteImport } from './routes/api/billing/summary'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingConsumeRouteImport } from './routes/api/billing/consume'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMcpTestServerIdRouteImport } from './routes/api/mcp/test/$serverId'
import { Route as ApiMcpReconnectServerIdRouteImport } from './routes/api/mcp/reconnect/$serverId'
import { Route as ApiMcpOauthCallbackRouteImport } from './routes/api/mcp/oauth/callback'
import { Route as ApiMcpEditServerIdRouteImport } from './routes/api/mcp/edit/$serverId'
import { Route as ApiMcpDisconnectServerIdRouteImport } from './routes/api/mcp/disconnect/$serverId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBillingRoute = ProtectedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiMcpServersRoute = ApiMcpServersRouteImport.update({
  id: '/api/mcp/servers',
  path: '/api/mcp/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpConnectRoute = ApiMcpConnectRouteImport.update({
  id: '/api/mcp/connect',
  path: '/api/mcp/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingSummaryRoute = ApiBillingSummaryRouteImport.update({
  id: '/api/billing/summary',
  path: '/api/billing/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingConsumeRoute = ApiBillingConsumeRouteImport.update({
  id: '/api/billing/consume',
  path: '/api/billing/consume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpTestServerIdRoute = ApiMcpTestServerIdRouteImport.update({
  id: '/api/mcp/test/$serverId',
  path: '/api/mcp/test/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpReconnectServerIdRoute = ApiMcpReconnectServerIdRouteImport.update({
  id: '/api/mcp/reconnect/$serverId',
  path: '/api/mcp/reconnect/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpOauthCallbackRoute = ApiMcpOauthCallbackRouteImport.update({
  id: '/api/mcp/oauth/callback',
  path: '/api/mcp/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpEditServerIdRoute = ApiMcpEditServerIdRouteImport.update({
  id: '/api/mcp/edit/$serverId',
  path: '/api/mcp/edit/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpDisconnectServerIdRoute =
  ApiMcpDisconnectServerIdRouteImport.update({
    id: '/api/mcp/disconnect/$serverId',
    path: '/api/mcp/disconnect/$serverId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/consume': typeof ApiBillingConsumeRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/summary': typeof ApiBillingSummaryRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/mcp/connect': typeof ApiMcpConnectRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/mcp/disconnect/$serverId': typeof ApiMcpDisconnectServerIdRoute
  '/api/mcp/edit/$serverId': typeof ApiMcpEditServerIdRoute
  '/api/mcp/oauth/callback': typeof ApiMcpOauthCallbackRoute
  '/api/mcp/reconnect/$serverId': typeof ApiMcpReconnectServerIdRoute
  '/api/mcp/test/$serverId': typeof ApiMcpTestServerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/consume': typeof ApiBillingConsumeRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/summary': typeof ApiBillingSummaryRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/mcp/connect': typeof ApiMcpConnectRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/mcp/disconnect/$serverId': typeof ApiMcpDisconnectServerIdRoute
  '/api/mcp/edit/$serverId': typeof ApiMcpEditServerIdRoute
  '/api/mcp/oauth/callback': typeof ApiMcpOauthCallbackRoute
  '/api/mcp/reconnect/$serverId': typeof ApiMcpReconnectServerIdRoute
  '/api/mcp/test/$serverId': typeof ApiMcpTestServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_protected/billing': typeof ProtectedBillingRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/consume': typeof ApiBillingConsumeRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/summary': typeof ApiBillingSummaryRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/mcp/connect': typeof ApiMcpConnectRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/mcp/disconnect/$serverId': typeof ApiMcpDisconnectServerIdRoute
  '/api/mcp/edit/$serverId': typeof ApiMcpEditServerIdRoute
  '/api/mcp/oauth/callback': typeof ApiMcpOauthCallbackRoute
  '/api/mcp/reconnect/$serverId': typeof ApiMcpReconnectServerIdRoute
  '/api/mcp/test/$serverId': typeof ApiMcpTestServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/billing'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/consume'
    | '/api/billing/portal'
    | '/api/billing/summary'
    | '/api/billing/webhook'
    | '/api/mcp/connect'
    | '/api/mcp/servers'
    | '/api/mcp/disconnect/$serverId'
    | '/api/mcp/edit/$serverId'
    | '/api/mcp/oauth/callback'
    | '/api/mcp/reconnect/$serverId'
    | '/api/mcp/test/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/billing'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/consume'
    | '/api/billing/portal'
    | '/api/billing/summary'
    | '/api/billing/webhook'
    | '/api/mcp/connect'
    | '/api/mcp/servers'
    | '/api/mcp/disconnect/$serverId'
    | '/api/mcp/edit/$serverId'
    | '/api/mcp/oauth/callback'
    | '/api/mcp/reconnect/$serverId'
    | '/api/mcp/test/$serverId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_protected/billing'
    | '/_protected/dashboard'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/consume'
    | '/api/billing/portal'
    | '/api/billing/summary'
    | '/api/billing/webhook'
    | '/api/mcp/connect'
    | '/api/mcp/servers'
    | '/api/mcp/disconnect/$serverId'
    | '/api/mcp/edit/$serverId'
    | '/api/mcp/oauth/callback'
    | '/api/mcp/reconnect/$serverId'
    | '/api/mcp/test/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingConsumeRoute: typeof ApiBillingConsumeRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingSummaryRoute: typeof ApiBillingSummaryRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiMcpConnectRoute: typeof ApiMcpConnectRoute
  ApiMcpServersRoute: typeof ApiMcpServersRoute
  ApiMcpDisconnectServerIdRoute: typeof ApiMcpDisconnectServerIdRoute
  ApiMcpEditServerIdRoute: typeof ApiMcpEditServerIdRoute
  ApiMcpOauthCallbackRoute: typeof ApiMcpOauthCallbackRoute
  ApiMcpReconnectServerIdRoute: typeof ApiMcpReconnectServerIdRoute
  ApiMcpTestServerIdRoute: typeof ApiMcpTestServerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/billing': {
      id: '/_protected/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ProtectedBillingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/mcp/servers': {
      id: '/api/mcp/servers'
      path: '/api/mcp/servers'
      fullPath: '/api/mcp/servers'
      preLoaderRoute: typeof ApiMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/connect': {
      id: '/api/mcp/connect'
      path: '/api/mcp/connect'
      fullPath: '/api/mcp/connect'
      preLoaderRoute: typeof ApiMcpConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/summary': {
      id: '/api/billing/summary'
      path: '/api/billing/summary'
      fullPath: '/api/billing/summary'
      preLoaderRoute: typeof ApiBillingSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/consume': {
      id: '/api/billing/consume'
      path: '/api/billing/consume'
      fullPath: '/api/billing/consume'
      preLoaderRoute: typeof ApiBillingConsumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/test/$serverId': {
      id: '/api/mcp/test/$serverId'
      path: '/api/mcp/test/$serverId'
      fullPath: '/api/mcp/test/$serverId'
      preLoaderRoute: typeof ApiMcpTestServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/reconnect/$serverId': {
      id: '/api/mcp/reconnect/$serverId'
      path: '/api/mcp/reconnect/$serverId'
      fullPath: '/api/mcp/reconnect/$serverId'
      preLoaderRoute: typeof ApiMcpReconnectServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/oauth/callback': {
      id: '/api/mcp/oauth/callback'
      path: '/api/mcp/oauth/callback'
      fullPath: '/api/mcp/oauth/callback'
      preLoaderRoute: typeof ApiMcpOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/edit/$serverId': {
      id: '/api/mcp/edit/$serverId'
      path: '/api/mcp/edit/$serverId'
      fullPath: '/api/mcp/edit/$serverId'
      preLoaderRoute: typeof ApiMcpEditServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/disconnect/$serverId': {
      id: '/api/mcp/disconnect/$serverId'
      path: '/api/mcp/disconnect/$serverId'
      fullPath: '/api/mcp/disconnect/$serverId'
      preLoaderRoute: typeof ApiMcpDisconnectServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedBillingRoute: typeof ProtectedBillingRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBillingRoute: ProtectedBillingRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingConsumeRoute: ApiBillingConsumeRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingSummaryRoute: ApiBillingSummaryRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiMcpConnectRoute: ApiMcpConnectRoute,
  ApiMcpServersRoute: ApiMcpServersRoute,
  ApiMcpDisconnectServerIdRoute: ApiMcpDisconnectServerIdRoute,
  ApiMcpEditServerIdRoute: ApiMcpEditServerIdRoute,
  ApiMcpOauthCallbackRoute: ApiMcpOauthCallbackRoute,
  ApiMcpReconnectServerIdRoute: ApiMcpReconnectServerIdRoute,
  ApiMcpTestServerIdRoute: ApiMcpTestServerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
