/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedBillingRouteImport } from './routes/_protected/billing'
import { Route as ApiMcpIndexRouteImport } from './routes/api/mcp/index'
import { Route as ApiMcpTestRouteImport } from './routes/api/mcp/test'
import { Route as ApiMcpIdRouteImport } from './routes/api/mcp/$id'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiBillingSummaryRouteImport } from './routes/api/billing/summary'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingConsumeRouteImport } from './routes/api/billing/consume'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMcpOauthStartRouteImport } from './routes/api/mcp/oauth/start'
import { Route as ApiMcpOauthDiscoverRouteImport } from './routes/api/mcp/oauth/discover'
import { Route as ApiMcpOauthCallbackRouteImport } from './routes/api/mcp/oauth/callback'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBillingRoute = ProtectedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiMcpIndexRoute = ApiMcpIndexRouteImport.update({
  id: '/api/mcp/',
  path: '/api/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpTestRoute = ApiMcpTestRouteImport.update({
  id: '/api/mcp/test',
  path: '/api/mcp/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpIdRoute = ApiMcpIdRouteImport.update({
  id: '/api/mcp/$id',
  path: '/api/mcp/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingSummaryRoute = ApiBillingSummaryRouteImport.update({
  id: '/api/billing/summary',
  path: '/api/billing/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingConsumeRoute = ApiBillingConsumeRouteImport.update({
  id: '/api/billing/consume',
  path: '/api/billing/consume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpOauthStartRoute = ApiMcpOauthStartRouteImport.update({
  id: '/api/mcp/oauth/start',
  path: '/api/mcp/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpOauthDiscoverRoute = ApiMcpOauthDiscoverRouteImport.update({
  id: '/api/mcp/oauth/discover',
  path: '/api/mcp/oauth/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpOauthCallbackRoute = ApiMcpOauthCallbackRouteImport.update({
  id: '/api/mcp/oauth/callback',
  path: '/api/mcp/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/consume': typeof ApiBillingConsumeRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/summary': typeof ApiBillingSummaryRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/mcp/$id': typeof ApiMcpIdRoute
  '/api/mcp/test': typeof ApiMcpTestRoute
  '/api/mcp/': typeof ApiMcpIndexRoute
  '/api/mcp/oauth/callback': typeof ApiMcpOauthCallbackRoute
  '/api/mcp/oauth/discover': typeof ApiMcpOauthDiscoverRoute
  '/api/mcp/oauth/start': typeof ApiMcpOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/consume': typeof ApiBillingConsumeRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/summary': typeof ApiBillingSummaryRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/mcp/$id': typeof ApiMcpIdRoute
  '/api/mcp/test': typeof ApiMcpTestRoute
  '/api/mcp': typeof ApiMcpIndexRoute
  '/api/mcp/oauth/callback': typeof ApiMcpOauthCallbackRoute
  '/api/mcp/oauth/discover': typeof ApiMcpOauthDiscoverRoute
  '/api/mcp/oauth/start': typeof ApiMcpOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_protected/billing': typeof ProtectedBillingRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/consume': typeof ApiBillingConsumeRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/summary': typeof ApiBillingSummaryRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/mcp/$id': typeof ApiMcpIdRoute
  '/api/mcp/test': typeof ApiMcpTestRoute
  '/api/mcp/': typeof ApiMcpIndexRoute
  '/api/mcp/oauth/callback': typeof ApiMcpOauthCallbackRoute
  '/api/mcp/oauth/discover': typeof ApiMcpOauthDiscoverRoute
  '/api/mcp/oauth/start': typeof ApiMcpOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/billing'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/consume'
    | '/api/billing/portal'
    | '/api/billing/summary'
    | '/api/billing/webhook'
    | '/api/mcp/$id'
    | '/api/mcp/test'
    | '/api/mcp/'
    | '/api/mcp/oauth/callback'
    | '/api/mcp/oauth/discover'
    | '/api/mcp/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/billing'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/consume'
    | '/api/billing/portal'
    | '/api/billing/summary'
    | '/api/billing/webhook'
    | '/api/mcp/$id'
    | '/api/mcp/test'
    | '/api/mcp'
    | '/api/mcp/oauth/callback'
    | '/api/mcp/oauth/discover'
    | '/api/mcp/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_protected/billing'
    | '/_protected/dashboard'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/consume'
    | '/api/billing/portal'
    | '/api/billing/summary'
    | '/api/billing/webhook'
    | '/api/mcp/$id'
    | '/api/mcp/test'
    | '/api/mcp/'
    | '/api/mcp/oauth/callback'
    | '/api/mcp/oauth/discover'
    | '/api/mcp/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingConsumeRoute: typeof ApiBillingConsumeRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingSummaryRoute: typeof ApiBillingSummaryRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiMcpIdRoute: typeof ApiMcpIdRoute
  ApiMcpTestRoute: typeof ApiMcpTestRoute
  ApiMcpIndexRoute: typeof ApiMcpIndexRoute
  ApiMcpOauthCallbackRoute: typeof ApiMcpOauthCallbackRoute
  ApiMcpOauthDiscoverRoute: typeof ApiMcpOauthDiscoverRoute
  ApiMcpOauthStartRoute: typeof ApiMcpOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/billing': {
      id: '/_protected/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ProtectedBillingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/mcp/': {
      id: '/api/mcp/'
      path: '/api/mcp'
      fullPath: '/api/mcp/'
      preLoaderRoute: typeof ApiMcpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/test': {
      id: '/api/mcp/test'
      path: '/api/mcp/test'
      fullPath: '/api/mcp/test'
      preLoaderRoute: typeof ApiMcpTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/$id': {
      id: '/api/mcp/$id'
      path: '/api/mcp/$id'
      fullPath: '/api/mcp/$id'
      preLoaderRoute: typeof ApiMcpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/summary': {
      id: '/api/billing/summary'
      path: '/api/billing/summary'
      fullPath: '/api/billing/summary'
      preLoaderRoute: typeof ApiBillingSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/consume': {
      id: '/api/billing/consume'
      path: '/api/billing/consume'
      fullPath: '/api/billing/consume'
      preLoaderRoute: typeof ApiBillingConsumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/oauth/start': {
      id: '/api/mcp/oauth/start'
      path: '/api/mcp/oauth/start'
      fullPath: '/api/mcp/oauth/start'
      preLoaderRoute: typeof ApiMcpOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/oauth/discover': {
      id: '/api/mcp/oauth/discover'
      path: '/api/mcp/oauth/discover'
      fullPath: '/api/mcp/oauth/discover'
      preLoaderRoute: typeof ApiMcpOauthDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/oauth/callback': {
      id: '/api/mcp/oauth/callback'
      path: '/api/mcp/oauth/callback'
      fullPath: '/api/mcp/oauth/callback'
      preLoaderRoute: typeof ApiMcpOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedBillingRoute: typeof ProtectedBillingRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBillingRoute: ProtectedBillingRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingConsumeRoute: ApiBillingConsumeRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingSummaryRoute: ApiBillingSummaryRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiMcpIdRoute: ApiMcpIdRoute,
  ApiMcpTestRoute: ApiMcpTestRoute,
  ApiMcpIndexRoute: ApiMcpIndexRoute,
  ApiMcpOauthCallbackRoute: ApiMcpOauthCallbackRoute,
  ApiMcpOauthDiscoverRoute: ApiMcpOauthDiscoverRoute,
  ApiMcpOauthStartRoute: ApiMcpOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
