/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedBillingRouteImport } from './routes/_protected/billing'
import { Route as ApiMcpServersRouteImport } from './routes/api/mcp/servers'
import { Route as ApiMcpDiscoverRouteImport } from './routes/api/mcp/discover'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiBillingSummaryRouteImport } from './routes/api/billing/summary'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingConsumeRouteImport } from './routes/api/billing/consume'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMcpServersUpdateRouteImport } from './routes/api/mcp/servers/update'
import { Route as ApiMcpServersTestRouteImport } from './routes/api/mcp/servers/test'
import { Route as ApiMcpServersDisconnectRouteImport } from './routes/api/mcp/servers/disconnect'
import { Route as ApiMcpAuthStartRouteImport } from './routes/api/mcp/auth/start'
import { Route as ApiMcpAuthCallbackRouteImport } from './routes/api/mcp/auth/callback'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBillingRoute = ProtectedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiMcpServersRoute = ApiMcpServersRouteImport.update({
  id: '/api/mcp/servers',
  path: '/api/mcp/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpDiscoverRoute = ApiMcpDiscoverRouteImport.update({
  id: '/api/mcp/discover',
  path: '/api/mcp/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingSummaryRoute = ApiBillingSummaryRouteImport.update({
  id: '/api/billing/summary',
  path: '/api/billing/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingConsumeRoute = ApiBillingConsumeRouteImport.update({
  id: '/api/billing/consume',
  path: '/api/billing/consume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpServersUpdateRoute = ApiMcpServersUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => ApiMcpServersRoute,
} as any)
const ApiMcpServersTestRoute = ApiMcpServersTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiMcpServersRoute,
} as any)
const ApiMcpServersDisconnectRoute = ApiMcpServersDisconnectRouteImport.update({
  id: '/disconnect',
  path: '/disconnect',
  getParentRoute: () => ApiMcpServersRoute,
} as any)
const ApiMcpAuthStartRoute = ApiMcpAuthStartRouteImport.update({
  id: '/api/mcp/auth/start',
  path: '/api/mcp/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpAuthCallbackRoute = ApiMcpAuthCallbackRouteImport.update({
  id: '/api/mcp/auth/callback',
  path: '/api/mcp/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/consume': typeof ApiBillingConsumeRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/summary': typeof ApiBillingSummaryRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/mcp/discover': typeof ApiMcpDiscoverRoute
  '/api/mcp/servers': typeof ApiMcpServersRouteWithChildren
  '/api/mcp/auth/callback': typeof ApiMcpAuthCallbackRoute
  '/api/mcp/auth/start': typeof ApiMcpAuthStartRoute
  '/api/mcp/servers/disconnect': typeof ApiMcpServersDisconnectRoute
  '/api/mcp/servers/test': typeof ApiMcpServersTestRoute
  '/api/mcp/servers/update': typeof ApiMcpServersUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/consume': typeof ApiBillingConsumeRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/summary': typeof ApiBillingSummaryRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/mcp/discover': typeof ApiMcpDiscoverRoute
  '/api/mcp/servers': typeof ApiMcpServersRouteWithChildren
  '/api/mcp/auth/callback': typeof ApiMcpAuthCallbackRoute
  '/api/mcp/auth/start': typeof ApiMcpAuthStartRoute
  '/api/mcp/servers/disconnect': typeof ApiMcpServersDisconnectRoute
  '/api/mcp/servers/test': typeof ApiMcpServersTestRoute
  '/api/mcp/servers/update': typeof ApiMcpServersUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_protected/billing': typeof ProtectedBillingRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/consume': typeof ApiBillingConsumeRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/summary': typeof ApiBillingSummaryRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/mcp/discover': typeof ApiMcpDiscoverRoute
  '/api/mcp/servers': typeof ApiMcpServersRouteWithChildren
  '/api/mcp/auth/callback': typeof ApiMcpAuthCallbackRoute
  '/api/mcp/auth/start': typeof ApiMcpAuthStartRoute
  '/api/mcp/servers/disconnect': typeof ApiMcpServersDisconnectRoute
  '/api/mcp/servers/test': typeof ApiMcpServersTestRoute
  '/api/mcp/servers/update': typeof ApiMcpServersUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/billing'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/consume'
    | '/api/billing/portal'
    | '/api/billing/summary'
    | '/api/billing/webhook'
    | '/api/mcp/discover'
    | '/api/mcp/servers'
    | '/api/mcp/auth/callback'
    | '/api/mcp/auth/start'
    | '/api/mcp/servers/disconnect'
    | '/api/mcp/servers/test'
    | '/api/mcp/servers/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/billing'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/consume'
    | '/api/billing/portal'
    | '/api/billing/summary'
    | '/api/billing/webhook'
    | '/api/mcp/discover'
    | '/api/mcp/servers'
    | '/api/mcp/auth/callback'
    | '/api/mcp/auth/start'
    | '/api/mcp/servers/disconnect'
    | '/api/mcp/servers/test'
    | '/api/mcp/servers/update'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_protected/billing'
    | '/_protected/dashboard'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/consume'
    | '/api/billing/portal'
    | '/api/billing/summary'
    | '/api/billing/webhook'
    | '/api/mcp/discover'
    | '/api/mcp/servers'
    | '/api/mcp/auth/callback'
    | '/api/mcp/auth/start'
    | '/api/mcp/servers/disconnect'
    | '/api/mcp/servers/test'
    | '/api/mcp/servers/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingConsumeRoute: typeof ApiBillingConsumeRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingSummaryRoute: typeof ApiBillingSummaryRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiMcpDiscoverRoute: typeof ApiMcpDiscoverRoute
  ApiMcpServersRoute: typeof ApiMcpServersRouteWithChildren
  ApiMcpAuthCallbackRoute: typeof ApiMcpAuthCallbackRoute
  ApiMcpAuthStartRoute: typeof ApiMcpAuthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/billing': {
      id: '/_protected/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ProtectedBillingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/mcp/servers': {
      id: '/api/mcp/servers'
      path: '/api/mcp/servers'
      fullPath: '/api/mcp/servers'
      preLoaderRoute: typeof ApiMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/discover': {
      id: '/api/mcp/discover'
      path: '/api/mcp/discover'
      fullPath: '/api/mcp/discover'
      preLoaderRoute: typeof ApiMcpDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/summary': {
      id: '/api/billing/summary'
      path: '/api/billing/summary'
      fullPath: '/api/billing/summary'
      preLoaderRoute: typeof ApiBillingSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/consume': {
      id: '/api/billing/consume'
      path: '/api/billing/consume'
      fullPath: '/api/billing/consume'
      preLoaderRoute: typeof ApiBillingConsumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/servers/update': {
      id: '/api/mcp/servers/update'
      path: '/update'
      fullPath: '/api/mcp/servers/update'
      preLoaderRoute: typeof ApiMcpServersUpdateRouteImport
      parentRoute: typeof ApiMcpServersRoute
    }
    '/api/mcp/servers/test': {
      id: '/api/mcp/servers/test'
      path: '/test'
      fullPath: '/api/mcp/servers/test'
      preLoaderRoute: typeof ApiMcpServersTestRouteImport
      parentRoute: typeof ApiMcpServersRoute
    }
    '/api/mcp/servers/disconnect': {
      id: '/api/mcp/servers/disconnect'
      path: '/disconnect'
      fullPath: '/api/mcp/servers/disconnect'
      preLoaderRoute: typeof ApiMcpServersDisconnectRouteImport
      parentRoute: typeof ApiMcpServersRoute
    }
    '/api/mcp/auth/start': {
      id: '/api/mcp/auth/start'
      path: '/api/mcp/auth/start'
      fullPath: '/api/mcp/auth/start'
      preLoaderRoute: typeof ApiMcpAuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/auth/callback': {
      id: '/api/mcp/auth/callback'
      path: '/api/mcp/auth/callback'
      fullPath: '/api/mcp/auth/callback'
      preLoaderRoute: typeof ApiMcpAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedBillingRoute: typeof ProtectedBillingRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBillingRoute: ProtectedBillingRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ApiMcpServersRouteChildren {
  ApiMcpServersDisconnectRoute: typeof ApiMcpServersDisconnectRoute
  ApiMcpServersTestRoute: typeof ApiMcpServersTestRoute
  ApiMcpServersUpdateRoute: typeof ApiMcpServersUpdateRoute
}

const ApiMcpServersRouteChildren: ApiMcpServersRouteChildren = {
  ApiMcpServersDisconnectRoute: ApiMcpServersDisconnectRoute,
  ApiMcpServersTestRoute: ApiMcpServersTestRoute,
  ApiMcpServersUpdateRoute: ApiMcpServersUpdateRoute,
}

const ApiMcpServersRouteWithChildren = ApiMcpServersRoute._addFileChildren(
  ApiMcpServersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingConsumeRoute: ApiBillingConsumeRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingSummaryRoute: ApiBillingSummaryRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiMcpDiscoverRoute: ApiMcpDiscoverRoute,
  ApiMcpServersRoute: ApiMcpServersRouteWithChildren,
  ApiMcpAuthCallbackRoute: ApiMcpAuthCallbackRoute,
  ApiMcpAuthStartRoute: ApiMcpAuthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
